### ISSUE TITLE
purestorage.flasharray.purefa_pg runs once 

### ISSUE THREAD

**Issue by joefodor** [Pure-Storage-Ansible/FlashArray-Collection#331]
**Describe the bug**
When running purestorage.flasharray.purefa_pg module I am only able to run it once. The first run is successful but the second one fails with an exception regrading the api_version is referenced before assignment
**To Reproduce**
1. run this module twice 
- name: Manage Protection Groups
  purestorage.flasharray.purefa_pg:
    pgroup: testgroup
    fa_url: "{{ purefa_auth.FA_URL }}"
    api_token: "{{ purefa_auth.FA_API_TOKEN }}"

<psa-v6-1> ESTABLISH LOCAL CONNECTION FOR USER: github
<psa-v6-1> EXEC /bin/sh -c 'echo ~github && sleep 0'
<psa-v6-1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/github/.ansible/tmp `"&& mkdir "` echo /home/github/.ansible/tmp/ansible-tmp-1665587554.3230028-5026-77352464413751 `" && echo ansible-tmp-1665587554.3230028-5026-77352464413751="` echo /home/github/.ansible/tmp/ansible-tmp-1665587554.3230028-5026-77352464413751 `" ) && sleep 0'
<psa-v6-3-5> ESTABLISH LOCAL CONNECTION FOR USER: github
<psa-v6-3-5> EXEC /bin/sh -c 'echo ~github && sleep 0'
<psa-v6-3-5> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/github/.ansible/tmp `"&& mkdir "` echo /home/github/.ansible/tmp/ansible-tmp-1665587554.3503792-5027-167067644314022 `" && echo ansible-tmp-1665587554.3503792-5027-167067644314022="` echo /home/github/.ansible/tmp/ansible-tmp-1665587554.3503792-5027-167067644314022 `" ) && sleep 0'
Using module file /home/github/.cache/ansible-compat/16e323/collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py
<psa-v6-1> PUT /home/github/.ansible/tmp/ansible-local-5002pkfhm712/tmpahlv72d0 TO /home/github/.ansible/tmp/ansible-tmp-1665587554.3230028-5026-77352464413751/AnsiballZ_purefa_pg.py
Using module file /home/github/.cache/ansible-compat/16e323/collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py
<psa-v6-1> EXEC /bin/sh -c 'chmod u+x /home/github/.ansible/tmp/ansible-tmp-1665587554.3230028-5026-77352464413751/ /home/github/.ansible/tmp/ansible-tmp-1665587554.3230028-5026-77352464413751/AnsiballZ_purefa_pg.py && sleep 0'
<psa-v6-3-5> PUT /home/github/.ansible/tmp/ansible-local-5002pkfhm712/tmpvszaru00 TO /home/github/.ansible/tmp/ansible-tmp-1665587554.3503792-5027-167067644314022/AnsiballZ_purefa_pg.py
<psa-v6-3-5> EXEC /bin/sh -c 'chmod u+x /home/github/.ansible/tmp/ansible-tmp-1665587554.3503792-5027-167067644314022/ /home/github/.ansible/tmp/ansible-tmp-1665587554.3503792-5027-167067644314022/AnsiballZ_purefa_pg.py && sleep 0'
<psa-v6-3-5> EXEC /bin/sh -c '/usr/bin/python3 /home/github/.ansible/tmp/ansible-tmp-1665587554.3503792-5027-167067644314022/AnsiballZ_purefa_pg.py && sleep 0'
<psa-v6-1> EXEC /bin/sh -c '/usr/bin/python3 /home/github/.ansible/tmp/ansible-tmp-1665587554.3230028-5026-77352464413751/AnsiballZ_purefa_pg.py && sleep 0'
<psa-v6-3-5> EXEC /bin/sh -c 'rm -f -r /home/github/.ansible/tmp/ansible-tmp-1665587554.3503792-5027-167067644314022/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/github/.ansible/tmp/ansible-tmp-1665587554.3503792-5027-167067644314022/AnsiballZ_purefa_pg.py", line 107, in <module>
    _ansiballz_main()
  File "/home/github/.ansible/tmp/ansible-tmp-1665587554.3503792-5027-167067644314022/AnsiballZ_purefa_pg.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/github/.ansible/tmp/ansible-tmp-1665587554.3503792-5027-167067644314022/AnsiballZ_purefa_pg.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.purestorage.flasharray.plugins.modules.purefa_pg', init_globals=dict(_module_fqn='ansible_collections.purestorage.flasharray.plugins.modules.purefa_pg', _modlib_path=modlib_path),
  File "/usr/local/lib/python3.9/runpy.py", line 225, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_purestorage.flasharray.purefa_pg_payload_jh8toqih/ansible_purestorage.flasharray.purefa_pg_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py", line 884, in <module>
  File "/tmp/ansible_purestorage.flasharray.purefa_pg_payload_jh8toqih/ansible_purestorage.flasharray.purefa_pg_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py", line 863, in main
  File "/tmp/ansible_purestorage.flasharray.purefa_pg_payload_jh8toqih/ansible_purestorage.flasharray.purefa_pg_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py", line 661, in update_pgroup
UnboundLocalError: local variable 'api_version' referenced before assignment
fatal: [psa-v6-3-5]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/github/.ansible/tmp/ansible-tmp-1665587554.3503792-5027-167067644314022/AnsiballZ_purefa_pg.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/github/.ansible/tmp/ansible-tmp-1665587554.3503792-5027-167067644314022/AnsiballZ_purefa_pg.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/github/.ansible/tmp/ansible-tmp-1665587554.3503792-5027-167067644314022/AnsiballZ_purefa_pg.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.purestorage.flasharray.plugins.modules.purefa_pg', init_globals=dict(_module_fqn='ansible_collections.purestorage.flasharray.plugins.modules.purefa_pg', _modlib_path=modlib_path),\n  File \"/usr/local/lib/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_purestorage.flasharray.purefa_pg_payload_jh8toqih/ansible_purestorage.flasharray.purefa_pg_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py\", line 884, in <module>\n  File \"/tmp/ansible_purestorage.flasharray.purefa_pg_payload_jh8toqih/ansible_purestorage.flasharray.purefa_pg_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py\", line 863, in main\n  File \"/tmp/ansible_purestorage.flasharray.purefa_pg_payload_jh8toqih/ansible_purestorage.flasharray.purefa_pg_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py\", line 661, in update_pgroup\nUnboundLocalError: local variable 'api_version' referenced before assignment\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
<psa-v6-1> EXEC /bin/sh -c 'rm -f -r /home/github/.ansible/tmp/ansible-tmp-1665587554.3230028-5026-77352464413751/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/github/.ansible/tmp/ansible-tmp-1665587554.3230028-5026-77352464413751/AnsiballZ_purefa_pg.py", line 107, in <module>
    _ansiballz_main()
  File "/home/github/.ansible/tmp/ansible-tmp-1665587554.3230028-5026-77352464413751/AnsiballZ_purefa_pg.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/github/.ansible/tmp/ansible-tmp-1665587554.3230028-5026-77352464413751/AnsiballZ_purefa_pg.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.purestorage.flasharray.plugins.modules.purefa_pg', init_globals=dict(_module_fqn='ansible_collections.purestorage.flasharray.plugins.modules.purefa_pg', _modlib_path=modlib_path),
  File "/usr/local/lib/python3.9/runpy.py", line 225, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_purestorage.flasharray.purefa_pg_payload__6pqbt7i/ansible_purestorage.flasharray.purefa_pg_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py", line 884, in <module>
  File "/tmp/ansible_purestorage.flasharray.purefa_pg_payload__6pqbt7i/ansible_purestorage.flasharray.purefa_pg_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py", line 863, in main
  File "/tmp/ansible_purestorage.flasharray.purefa_pg_payload__6pqbt7i/ansible_purestorage.flasharray.purefa_pg_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py", line 661, in update_pgroup
UnboundLocalError: local variable 'api_version' referenced before assignment
fatal: [psa-v6-1]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/github/.ansible/tmp/ansible-tmp-1665587554.3230028-5026-77352464413751/AnsiballZ_purefa_pg.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/github/.ansible/tmp/ansible-tmp-1665587554.3230028-5026-77352464413751/AnsiballZ_purefa_pg.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/github/.ansible/tmp/ansible-tmp-1665587554.3230028-5026-77352464413751/AnsiballZ_purefa_pg.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.purestorage.flasharray.plugins.modules.purefa_pg', init_globals=dict(_module_fqn='ansible_collections.purestorage.flasharray.plugins.modules.purefa_pg', _modlib_path=modlib_path),\n  File \"/usr/local/lib/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_purestorage.flasharray.purefa_pg_payload__6pqbt7i/ansible_purestorage.flasharray.purefa_pg_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py\", line 884, in <module>\n  File \"/tmp/ansible_purestorage.flasharray.purefa_pg_payload__6pqbt7i/ansible_purestorage.flasharray.purefa_pg_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py\", line 863, in main\n  File \"/tmp/ansible_purestorage.flasharray.purefa_pg_payload__6pqbt7i/ansible_purestorage.flasharray.purefa_pg_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py\", line 661, in update_pgroup\nUnboundLocalError: local variable 'api_version' referenced before assignment\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Ansible Version:
ansible [core 2.13.1]
  config file = None
  configured module search path = ['/home/github/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/github/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.14 (main, Sep 13 2022, 14:57:28) [GCC 8.3.0]
  jinja version = 3.1.2
  libyaml = True

purestorage==1.19.0

**Additional context**

**Comment by sdodsley** [comment]
@joefodor please confirm you are running the latest FlashArray Collection by sing the following command:
`ansible-galaxy collection install purestorage.flasharray --force`

**Comment by joefodor** [comment]
@sdodsley Thanks for quick reply. I ran the galaxy command and got the 1.14 I was on 1.13 but I am getrting the same error 

This error is confusing line 661 in purefa_pg isnt referencing the api_version.  Line 654 is.

The full traceback is:
Traceback (most recent call last):
  File "/home/github/.ansible/tmp/ansible-tmp-1665589469.420417-803-170882282584533/AnsiballZ_purefa_pg.py", line 107, in <module>
    _ansiballz_main()
  File "/home/github/.ansible/tmp/ansible-tmp-1665589469.420417-803-170882282584533/AnsiballZ_purefa_pg.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/github/.ansible/tmp/ansible-tmp-1665589469.420417-803-170882282584533/AnsiballZ_purefa_pg.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.purestorage.flasharray.plugins.modules.purefa_pg', init_globals=dict(_module_fqn='ansible_collections.purestorage.flasharray.plugins.modules.purefa_pg', _modlib_path=modlib_path),
  File "/usr/local/lib/python3.9/runpy.py", line 225, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_purestorage.flasharray.purefa_pg_payload_j8970m_k/ansible_purestorage.flasharray.purefa_pg_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py", line 884, in <module>
  File "/tmp/ansible_purestorage.flasharray.purefa_pg_payload_j8970m_k/ansible_purestorage.flasharray.purefa_pg_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py", line 863, in main
  File "/tmp/ansible_purestorage.flasharray.purefa_pg_payload_j8970m_k/ansible_purestorage.flasharray.purefa_pg_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py", line 661, in update_pgroup
UnboundLocalError: local variable 'api_version' referenced before assignment
fatal: [psa-v6-1]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/github/.ansible/tmp/ansible-tmp-1665589469.420417-803-170882282584533/AnsiballZ_purefa_pg.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/github/.ansible/tmp/ansible-tmp-1665589469.420417-803-170882282584533/AnsiballZ_purefa_pg.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/github/.ansible/tmp/ansible-tmp-1665589469.420417-803-170882282584533/AnsiballZ_purefa_pg.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.purestorage.flasharray.plugins.modules.purefa_pg', init_globals=dict(_module_fqn='ansible_collections.purestorage.flasharray.plugins.modules.purefa_pg', _modlib_path=modlib_path),\n  File \"/usr/local/lib/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/local/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_purestorage.flasharray.purefa_pg_payload_j8970m_k/ansible_purestorage.flasharray.purefa_pg_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py\", line 884, in <module>\n  File \"/tmp/ansible_purestorage.flasharray.purefa_pg_payload_j8970m_k/ansible_purestorage.flasharray.purefa_pg_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py\", line 863, in main\n  File \"/tmp/ansible_purestorage.flasharray.purefa_pg_payload_j8970m_k/ansible_purestorage.flasharray.purefa_pg_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py\", line 661, in update_pgroup\nUnboundLocalError: local variable 'api_version' referenced before assignment\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by sdodsley** [comment]
In your playbook can you ensure you are referencing the FQCN, so use `purestorage.flasharray.purefa_pg`

**Comment by sdodsley** [comment]
Can you show the output from `ansible-galaxy collection list` please?

**Comment by joefodor** [comment]
# /usr/share/ansible/collections/ansible_collections
Collection             Version
---------------------- -------
ansible.utils          2.6.1  
community.general      5.5.0  
community.vmware       2.3.0  
infoblox.nios_modules  1.3.0  
purestorage.flasharray 1.13.0 

# /home/github/.ansible/collections/ansible_collections
Collection             Version
---------------------- -------
purestorage.flasharray 1.14.0

**Comment by sdodsley** [comment]
So 1.14.0 has this fix in it. Not sure why your playbook is using the unpatched 1.13.0 version.

**Comment by joefodor** [comment]
I rebuilt my container to only use the 1.14.0 still getting that same error. I will keep digging thanks for the help

**Comment by sdodsley** [comment]
Closing due to lack of activity
