### ISSUE TITLE
purefa_info host subset erroring out looking for a key referencing a target array host

### ISSUE THREAD

**Issue by StephenEGibson** [Pure-Storage-Ansible/FlashArray-Collection#456]
**Describe the bug**
purefa_info is erroring out with what appears to be a lookup for a host on the target system

**To Reproduce**
        - name: Retrieving Host Information
          purestorage.flasharray.purefa_info:
            gather_subset:
              - hosts                      
            fa_url: "{{ fa_url }}"
            api_token: "{{ api_token }}"
          register: "hosts_info"

**Expected behavior**
The module returns the info for the hosts on the local system.

**Screenshots**
   Traceback (most recent call last):
      File "AnsiballZ_purefa_info.py", line 107, in <module>
        _ansiballz_main()
      File "AnsiballZ_purefa_info.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "AnsiballZ_purefa_info.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.purestorage.flasharray.plugins.modules.purefa_info', init_globals=dict(_module_fqn='ansible_collections.purestorage.flasharray.plugins.modules.purefa_info', _modlib_path=modlib_path),
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 224, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "/var/folders/1w/1v06sfjj7y7f26jb1sh0hzqc7h7c0v/T/ansible_purestorage.flasharray.purefa_info_payload_0sp223ra/ansible_purestorage.flasharray.purefa_info_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_info.py", line 2363, in <module>
      File "/var/folders/1w/1v06sfjj7y7f26jb1sh0hzqc7h7c0v/T/ansible_purestorage.flasharray.purefa_info_payload_0sp223ra/ansible_purestorage.flasharray.purefa_info_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_info.py", line 2288, in main
      File "/var/folders/1w/1v06sfjj7y7f26jb1sh0hzqc7h7c0v/T/ansible_purestorage.flasharray.purefa_info_payload_0sp223ra/ansible_purestorage.flasharray.purefa_info_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_info.py", line 1289, in generate_host_dict
    KeyError: '<target_array>:<host_name>'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

**Desktop (please complete the following information):**
 - purestorage.flasharray 1.21.0
 - python 3.10.7
 - ansible core 2.14.2
 - purity 6.4.10

**Comment by sdodsley** [comment]
Please see if #447 resolves this for you

**Comment by StephenEGibson** [comment]
This resolves it. Thanks!
