### ISSUE TITLE
Module Failure on purefa_info

### ISSUE THREAD

**Issue by nurseandthenerd** [Pure-Storage-Ansible/FlashArray-Collection#616]
**Describe the bug**
Issue seems to have developed after upgrading to Purity 6.5.7. However that could have been a coincidence. No changes to the code have been made, but all of the sudden the module is failing both from Ansible Automation Platform and my local machine. 

AttributeError: 'VolumeSpaceCommon' object has no attribute 'total_used'

**To Reproduce**

- name: Collect All {{storagearray.name}} Info
  purestorage.flasharray.purefa_info:
    gather_subset:
      - hgroups
      - hosts
      - vgroups
      - volumes
    fa_url: "{{storagearray.fqdn}}"
    api_token: "{{token.json.api_token}}"
    disable_warnings: True
  delegate_to: localhost
  run_once: true
  register: pure_array_info

**Expected behavior**
Module returns data

**Screenshots**
![image](https://github.com/user-attachments/assets/ac2d9e01-85cb-44ac-9750-489b857a8d36)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version: purestorage.flasharray:1.30.2

**Additional context**
Full error output: 

The full traceback is:
Traceback (most recent call last):
  File "/home/pat/.ansible/tmp/ansible-tmp-1723658018.8533597-1322423-54862595050628/AnsiballZ_purefa_info.py", line 107, in <module>
    _ansiballz_main()
  File "/home/pat/.ansible/tmp/ansible-tmp-1723658018.8533597-1322423-54862595050628/AnsiballZ_purefa_info.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/pat/.ansible/tmp/ansible-tmp-1723658018.8533597-1322423-54862595050628/AnsiballZ_purefa_info.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.purestorage.flasharray.plugins.modules.purefa_info', init_globals=dict(_module_fqn='ansible_collections.purestorage.flasharray.plugins.modules.purefa_info', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_purestorage.flasharray.purefa_info_payload_0mn9e03o/ansible_purestorage.flasharray.purefa_info_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_info.py", line 3171, in <module>
  File "/tmp/ansible_purestorage.flasharray.purefa_info_payload_0mn9e03o/ansible_purestorage.flasharray.purefa_info_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_info.py", line 3093, in main
  File "/tmp/ansible_purestorage.flasharray.purefa_info_payload_0mn9e03o/ansible_purestorage.flasharray.purefa_info_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_info.py", line 1433, in generate_vol_dict
  File "/home/pat/.local/lib/python3.8/site-packages/pypureclient/flasharray/FA_2_10/models/volume_space_common.py", line 167, in __getattribute__
    value = object.__getattribute__(self, item)
AttributeError: 'VolumeSpaceCommon' object has no attribute 'total_used'
fatal: [biggs-autodeploy-dhcp -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/pat/.ansible/tmp/ansible-tmp-1723658018.8533597-1322423-54862595050628/AnsiballZ_purefa_info.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/pat/.ansible/tmp/ansible-tmp-1723658018.8533597-1322423-54862595050628/AnsiballZ_purefa_info.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/pat/.ansible/tmp/ansible-tmp-1723658018.8533597-1322423-54862595050628/AnsiballZ_purefa_info.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.purestorage.flasharray.plugins.modules.purefa_info', init_globals=dict(_module_fqn='ansible_collections.purestorage.flasharray.plugins.modules.purefa_info', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_purestorage.flasharray.purefa_info_payload_0mn9e03o/ansible_purestorage.flasharray.purefa_info_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_info.py\", line 3171, in <module>\n  File \"/tmp/ansible_purestorage.flasharray.purefa_info_payload_0mn9e03o/ansible_purestorage.flasharray.purefa_info_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_info.py\", line 3093, in main\n  File \"/tmp/ansible_purestorage.flasharray.purefa_info_payload_0mn9e03o/ansible_purestorage.flasharray.purefa_info_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_info.py\", line 1433, in generate_vol_dict\n  File \"/home/pat/.local/lib/python3.8/site-packages/pypureclient/flasharray/FA_2_10/models/volume_space_common.py\", line 167, in __getattribute__\n    value = object.__getattribute__(self, item)\nAttributeError: 'VolumeSpaceCommon' object has no attribute 'total_used'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by sdodsley** [comment]
Please check you have upgraded the py-pure-client SDK to the latest version and try again.

**Comment by nurseandthenerd** [comment]
That did it. Thank you for your assistance.
